### ISSUE TITLE
World Corruption

### ISSUE THREAD

**Issue by JohnnyBlazzed** [DrummingFish/MonumentalModpack#17]
After quit a bit of playtime with the mod-pack on a game I opened to LAN and was playing with my siblings, suddenly the world was corrupted. I was AFK at the time, as was my brother, and we were the only ones on, so nothing new had happened. 

Time: 10/28/15 11:12 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:18)
    at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:93)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:18)
    at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:93)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)

**Comment by JohnnyBlazzed** [comment]
A small update. I sent the world save to my brother. He opened it and it did not crash when he loaded it. He had all of my stuff on him. But, the village we had populated shrunk, and nothing we had done to it was there. It basically reset the world gen.
